apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: cert-manager
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  inputs:
    - interval: "1h" # check for updates every hour
      version: "*" # upgrade to latest stable version
      namespace: cert-manager
  commonMetadata:
    labels:
      toolkit.fluxcd.io/tenant: platform-team
  wait: true
  resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: << inputs.namespace >>
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      metadata:
        name: << inputs.provider.name >>
        namespace: << inputs.namespace >>
      spec:
        interval: << inputs.interval | quote >>
        url: oci://quay.io/jetstack/charts/cert-manager
        layerSelector:
          mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
          operation: copy
        ref:
          semver: << inputs.version | quote >>
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: << inputs.provider.name >>
        namespace: << inputs.namespace >>
      spec:
        interval: 12h
        install:
          strategy:
            name: RetryOnFailure
            retryInterval: 2m
        upgrade:
          strategy:
            name: RetryOnFailure
            retryInterval: 3m
        releaseName: << inputs.provider.name >>
        chartRef:
          kind: OCIRepository
          name: << inputs.provider.name >>
        values:
          crds:
            enabled: true
            keep: false
